[phases.setup]
nixPkgs = [
    "python311",
    "wkhtmltopdf",
    "xvfb-run",
    "fontconfig",
    "freetype",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender"
]

[variables]
GI_TYPELIB_PATH = "/nix/store/*/lib/girepository-1.0"
LD_LIBRARY_PATH = "/nix/store/*/lib"
PKG_CONFIG_PATH = "/nix/store/*/lib/pkgconfig"
FONTCONFIG_PATH = "/nix/store/*/etc/fonts"

[start]
cmd = "gunicorn app:app" 