[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn app:app"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig]
"us-west2" = { numReplicas = 1 }

# Cron service for StreetEasy scraping
[[services]]
name = "scrape-streeteasy"
type = "cron"
schedule = "07 16 * * *"  # Runs at 4:03 PM every day
command = "PYTHONPATH=$PYTHONPATH:. python Services/Streeteasy/scrape_streeteasy.py"
